_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 71
                - 83
            "2":
                - 1
                - 41
                - 49
                - 55
                - 71
                - 83
            "3":
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "8":
                - 2
                - 5
            "12": 0.19.7
            "13": linux-x86_64
